=== sakella6669/crudgenerator/trunk/crudgenerator/src/main/java/com/bupt/liutong/generator2/config/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3school.com.cn" xmlns="http://www.w3school.com.cn"
	elementFormDefault="qualified">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="db" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="driverClass" type="xs:string"
							use="required" />
						<xs:attribute name="jdbcUrl" type="xs:string" use="required" />
						<xs:attribute name="userId" type="xs:string" use="required" />
						<xs:attribute name="password" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="templates" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="template" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="path" type="xs:string" use="required" />
									<xs:attribute name="targetPath" type="xs:string" use="required" />
									<xs:attribute name="transform" type="xs:string" default="table" />
									<xs:attribute name="override" type="xs:boolean" default="false" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="parameters" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="parameter" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:string" use="required" />
									<xs:attribute name="value" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sakella6669/crudgenerator/crudgenerator/src/main/java/com/bupt/liutong/generator/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://localhost/schema/config" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://localhost/schema/config config.xsd">
	<db driverClass="com.mysql.jdbc.Driver"
		jdbcUrl="jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf8"
		userId="root" password="sa" />

	<templates>
		<!-- generated layer code -->
		<template path="src/main/java/com/bupt/liutong/generator/template/dto.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/dto/${table.clazz}.java" />
		<template path="src/main/java/com/bupt/liutong/generator/template/form.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/form/${table.clazz}Form.java" />
		<template path="src/main/java/com/bupt/liutong/generator/template/gen_dao.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/dao/gen/Gen${table.clazz}Dao.java" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/gen_sqlmap.xml.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/sqlmap/gen/gen_${table.name}.xml" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/gen_bo.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/bo/gen/Gen${table.clazz}Bo.java" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/gen_action.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/action/gen/Gen${table.clazz}Action.java"
			override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/list.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_list.jsp" />
		<template path="src/main/java/com/bupt/liutong/generator/template/list_head.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_list_head.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/list_query.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_list_query.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/list_result.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_list_result.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/insert.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_insert.jsp" />
		<template path="src/main/java/com/bupt/liutong/generator/template/insert_head.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_insert_head.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/insert_input.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_insert_input.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/update.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_update.jsp" />
		<template path="src/main/java/com/bupt/liutong/generator/template/update_head.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_update_head.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/update_input.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_update_input.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/ddl.sql.xsl"
			targetPath="sql/${table.name}.sql" override="true" />
			
		<!-- written layer code -->
		<template path="src/main/java/com/bupt/liutong/generator/template/dao.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/dao/${table.clazz}Dao.java" />
		<template path="src/main/java/com/bupt/liutong/generator/template/sqlmap.xml.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/sqlmap/${table.name}.xml" />
		<template path="src/main/java/com/bupt/liutong/generator/template/bo.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/bo/${table.clazz}Bo.java" />
		<template path="src/main/java/com/bupt/liutong/generator/template/action.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/action/${table.clazz}Action.java" />

		<!-- almost static code -->
		<template path="src/main/java/com/bupt/liutong/generator/template/web.xml.xsl"
			targetPath="WebRoot/WEB-INF/web.xml" transform="model" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/.project.xsl"
			targetPath=".project" transform="config" />
		<template path="src/main/java/com/bupt/liutong/generator/template/pom.xml.xsl"
			targetPath="pom.xml" transform="config" />
		<template path="src/main/java/com/bupt/liutong/generator/template/ibatis.xml.xsl"
			targetPath="src/main/resources/ibatis.xml" transform="model" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/struts.xml.xsl"
			targetPath="src/main/resources/struts.xml" transform="model" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/struts-package.xml.xsl"
			targetPath="src/main/resources/struts-${package}.xml" transform="package" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/spring.xml.xsl"
			targetPath="src/main/resources/spring.xml" transform="config" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/spring-gen-package.xml.xsl"
			targetPath="src/main/resources/spring-gen-${package}.xml" transform="package" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator/template/spring-package.xml.xsl"
			targetPath="src/main/resources/spring-${package}.xml" transform="package" override="true" />
	</templates>

	<parameters>
		<parameter id="genPrefixUpper" value="Gen" />
		<parameter id="genPrefixLower" value="gen_" />
		<parameter id="baseDir" value="com/bupt/liutong" />
		<parameter id="basePackage" value="com.bupt.liutong" />
		<parameter id="prjName" value="result" />
		<parameter id="targetPrj" value="E:\WorkSpace_OSGi\result" />
	</parameters>
</config>

=== sakella6669/crudgenerator/trunk/crudgenerator/src/main/java/com/bupt/liutong/generator2/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3school.com.cn config.xsd">
	<db driverClass="com.mysql.jdbc.Driver"
		jdbcUrl="jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf8"
		userId="root" password="sa" />

	<templates>
		<!-- dynamic generated code -->
		<template path="src/main/java/com/bupt/liutong/generator2/template/dto.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/dto/${table.clazz}.java" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/form.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/form/${table.clazz}Form.java" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/gen_dao.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/dao/gen/Gen${table.clazz}Dao.java" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/gen_sqlmap.xml.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/sqlmap/gen/gen_${table.name}.xml" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/gen_bo.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/bo/gen/Gen${table.clazz}Bo.java" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/gen_action.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/action/gen/Gen${table.clazz}Action.java"
			override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/list.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_list.jsp" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/list_head.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_list_head.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/list_query.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_list_query.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/list_result.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_list_result.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/insert.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_insert.jsp" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/insert_head.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_insert_head.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/insert_input.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_insert_input.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/update.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_update.jsp" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/update_head.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_update_head.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/update_input.jsp.xsl"
			targetPath="WebRoot/${package}/${table.clazz.lower}/${table.name}_update_input.jsp" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/ddl.sql.xsl"
			targetPath="sql/${table.name}.sql" override="true" />
			
		<!-- written generated layer -->
		<template path="src/main/java/com/bupt/liutong/generator2/template/dao.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/dao/${table.clazz}Dao.java" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/sqlmap.xml.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/sqlmap/${table.name}.xml" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/bo.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/bo/${table.clazz}Bo.java" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/action.java.xsl"
			targetPath="src/main/java/com/bupt/liutong/${package}/action/${table.clazz}Action.java" />

		<!-- dynamic generated config -->
		<template path="src/main/java/com/bupt/liutong/generator2/template/web.xml.xsl"
			targetPath="WebRoot/WEB-INF/web.xml" transform="model" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/.project.xsl"
			targetPath=".project" transform="config" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/pom.xml.xsl"
			targetPath="pom.xml" transform="config" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/ibatis.xml.xsl"
			targetPath="src/main/resources/ibatis.xml" transform="model" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/struts.xml.xsl"
			targetPath="src/main/resources/struts.xml" transform="model" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/struts-package.xml.xsl"
			targetPath="src/main/resources/struts-${package}.xml" transform="package" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/spring.xml.xsl"
			targetPath="src/main/resources/spring.xml" transform="config" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/spring-gen-package.xml.xsl"
			targetPath="src/main/resources/spring-gen-${package}.xml" transform="package" override="true" />
		<template path="src/main/java/com/bupt/liutong/generator2/template/spring-package.xml.xsl"
			targetPath="src/main/resources/spring-${package}.xml" transform="package" override="true" />
	</templates>

	<parameters>
		<parameter id="genPrefixUpper" value="Gen" />
		<parameter id="genPrefixLower" value="gen_" />
		<parameter id="baseDir" value="com/bupt/liutong" />
		<parameter id="basePackage" value="com.bupt.liutong" />
		<parameter id="prjName" value="result" />
		<parameter id="targetPrj" value="F:\temp\result" />
	</parameters>
</config>
