=== sakella6669/crudgenerator/trunk/crudgenerator/src/main/java/com/bupt/liutong/generator2/config/model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://localhost/schema/model" xmlns="http://localhost/schema/model"
	elementFormDefault="qualified">
	<xs:element name="model">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="package" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="table" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="import" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="clazz" type="xs:string"
													use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="column" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="field" type="xs:string" use="required" />
												<xs:attribute name="chs" type="xs:string" use="required" />
												<xs:attribute name="dbType" type="xs:string" />
												<xs:attribute name="javaType" type="xs:string" default="String" />
												<xs:attribute name="length" type="xs:positiveInteger" />
												<xs:attribute name="defaultValue" type="xs:string"
													default="" />
												<xs:attribute name="itemType" type="xs:positiveInteger"
													default="10" />
												<xs:attribute name="inputItem" type="xs:boolean"
													default="true" />
												<xs:attribute name="queryItem" type="xs:boolean"
													default="false" />
												<xs:attribute name="listDisp" type="xs:boolean"
													default="false" />
												<xs:attribute name="mustInput" type="xs:boolean"
													default="false" />
												<xs:attribute name="notNull" type="xs:boolean"
													default="true" />
												<xs:attribute name="isPrimary" type="xs:boolean"
													default="false" />
												<xs:attribute name="autoIncrement" type="xs:boolean"
													default="false" />
												<xs:attribute name="codeMapping" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="clazz" type="xs:string" use="required" />
									<xs:attribute name="chs" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sakella6669/crudgenerator/trunk/crudgenerator/src/main/java/com/bupt/liutong/generator/config/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://localhost/schema/model" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://localhost/schema/model model.xsd">
	<package name="myapp">
		<table clazz="Tag" chs="标签">
			<column field="id" chs="标签id" javaType="Integer" 
				inputItem="false" isPrimary="true" autoIncrement="true" />
			<column field="name" chs="标签名" listDisp="true" />
			<column field="parentId" chs="上级标签id" javaType="Integer"
				itemType="60" defaultValue="-1" 
				joinTable="Tag" joinField="id" joinLabelField="name" />
		</table>
	</package>
	<package name="right">
		<table clazz="User" chs="用户">
			<column field="id" chs="用户id" javaType="Integer"
				inputItem="false" isPrimary="true" autoIncrement="true" 
				m2mJoinTable="Role" m2mJoinField="id" m2mJoinLabelField="name"
				m2mAutoGen="true" />
			<column field="name" chs="账号" />
		</table>
		<table clazz="Role" chs="角色">
			<column field="id" chs="角色id" javaType="Integer" 
				inputItem="false" isPrimary="true" autoIncrement="true"/>
			<column field="name" chs="角色名" />
		</table>
	</package>
	<package name="bbs">
		<table clazz="Board" chs="版块">
			<column field="id" chs="版块id" javaType="Integer" 
				inputItem="false" isPrimary="true" autoIncrement="true" />
			<column field="parentId" chs="父版块id" javaType="Integer"
				defaultValue="-1" />
			<column field="name" chs="版块名称"
				length="60" mustInput="true" queryItem="true" listDisp="true" />
			<column field="des" chs="描述" dbType="text"
				itemType="40" />
			<column field="enabled" chs="是否显示" dbType="tinyint" javaType="Integer"
				itemType="50" listDisp="true" codeMapping="ifDisp" />
			<column field="seq" chs="顺序号" dbType="tinyint" javaType="Integer" 
				length="4" defaultValue="10" itemType="20" listDisp="true" />
			<column field="needPassword" chs="是否需要密码" dbType="tinyint" javaType="Integer"
				itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column field="password" chs="密码" 
				length="30" />
			<column field="auth" chs="是否需要密码" dbType="tinyint" javaType="Integer"
				itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column field="level" chs="版块层级" dbType="tinyint" javaType="Integer" length="2" />
			<column field="mainPostNum" chs="发帖数" javaType="Integer" />
			<column field="postNum" chs="总帖数" javaType="Integer" />
		</table>
		<table clazz="Post" chs="帖子">
			<column field="id" chs="帖子id" javaType="Long" 
				inputItem="false" isPrimary="true" autoIncrement="true" />
			<column field="parentId" chs="主帖id" javaType="Long"
				inputItem="true" defaultValue="-1" />
			<column field="boardId" chs="版块id" javaType="Integer"
				itemType="60" joinTable="Board" joinField="id" joinLabelField="name" />
			<column field="title" chs="标题"
				length="150" mustInput="true" queryItem="true" listDisp="true" />
			<column field="replyNum" chs="回复数" javaType="Integer"
				inputItem="false" defaultValue="0" />
			<column field="clickNum" chs="点击数" javaType="Integer"
				inputItem="false" defaultValue="0" />
			<column field="userName" chs="发帖人id"
				length="30" listDisp="true" />
			<column field="nickName" chs="发帖人"
				length="30" listDisp="true" />
			<column field="content" chs="帖子内容" dbType="text" javaType="String"
				itemType="40" listDisp="true" />
			<column field="createTime" chs="发帖时间" dbType="datetime" javaType="Date"
				itemType="30" listDisp="true" />
			<column field="ip" chs="ip" dbType="char" javaType="String"
				length="15" />
			<column field="lastReplyTime" chs="最后回帖时间" dbType="datetime" javaType="Date"
				itemType="30" listDisp="true" />
			<column field="lastUserName" chs="最后发帖人id"
				length="30" />
			<column field="lastNickName" chs="最后发帖人"
				length="30" />
			<column field="elite" chs="是否精华" dbType="tinyint" javaType="Integer"
				itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column field="top" chs="是否置顶" dbType="tinyint" javaType="Integer"
				itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column field="locked" chs="是否锁定" dbType="tinyint" javaType="Integer"
				itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column field="hidden" chs="是否隐藏" dbType="tinyint" javaType="Integer"
				itemType="50" listDisp="true" codeMapping="yesOrNo" />
		</table>
	</package>
</model>

=== sakella6669/crudgenerator/trunk/crudgenerator/src/main/java/com/bupt/liutong/generator2/config/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3school.com.cn model.xsd">
	<package name="bbs">
		<table name="bbs_board" clazz="Board" chs="版块">
			<column name="id" field="id" chs="版块id" dbType="int" javaType="Integer" length="11"
				inputItem="false" isPrimary="true" autoIncrement="true" />
			<column name="parentId" field="parentId" chs="父版块id" dbType="int" javaType="Integer"
				length="11" defaultValue="-1" />
			<column name="name" field="name" chs="版块名称" dbType="varchar" javaType="String"
				length="60" itemType="10" mustInput="true" listDisp="true" />
			<column name="des" field="des" chs="描述" dbType="text" javaType="String"
				itemType="40" />
			<column name="enabled" field="enabled" chs="是否显示" dbType="tinyint" javaType="Integer"
				length="1" itemType="50" listDisp="true" codeMapping="ifDisp" />
			<column name="seq" field="seq" chs="顺序号" dbType="tinyint" javaType="Integer" length="4"
				defaultValue="10" itemType="20" listDisp="true" />
			<column name="needPassword" field="needPassword" chs="是否需要密码" dbType="tinyint" javaType="Integer"
				length="1" itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column name="password" field="password" chs="密码" dbType="varchar" javaType="String"
				length="30" itemType="10" />
			<column name="auth" field="auth" chs="是否需要密码" dbType="tinyint" javaType="Integer"
				length="1" itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column name="level" field="level" chs="版块层级" dbType="tinyint" javaType="Integer" length="2" />
			<column name="mainPostNum" field="mainPostNum" chs="发帖数" dbType="int" javaType="Integer" length="11" />
			<column name="postNum" field="postNum" chs="总帖数" dbType="int" javaType="Integer" length="11" />
		</table>
		<table name="bbs_post" clazz="Post" chs="帖子">
			<import clazz="java.util.Date" />
			<import clazz="com.bupt.liutong.util.DateUtils" />
			<column name="id" field="id" chs="帖子id" dbType="bigint" javaType="Long" length="20"
				inputItem="false" isPrimary="true" autoIncrement="true" />
			<column name="parentId" field="parentId" chs="主帖id" dbType="bigint" javaType="Long"
				length="20" inputItem="false" />
			<column name="boardId" field="boardId" chs="板块id" dbType="int" javaType="Integer"
				length="11" inputItem="false" />
			<column name="title" field="title" chs="标题" dbType="varchar" javaType="String"
				length="150" itemType="10" mustInput="true" queryItem="true" listDisp="true" />
			<column name="replyNum" field="replyNum" chs="回复数" dbType="int" javaType="Integer"
				length="11" inputItem="false" />
			<column name="clickNum" field="clickNum" chs="点击数" dbType="int" javaType="Integer"
				length="11" inputItem="false" />
			<column name="userName" field="userName" chs="发帖人id" dbType="varchar" javaType="String"
				length="30" itemType="10" listDisp="true" />
			<column name="nickName" field="nickName" chs="发帖人" dbType="varchar" javaType="String"
				length="30" itemType="10" listDisp="true" />
			<column name="content" field="content" chs="帖子内容" dbType="text" javaType="String"
				itemType="40" listDisp="true" />
			<column name="createTime" field="createTime" chs="发帖时间" dbType="datetime" javaType="Date"
				itemType="30" listDisp="true" />
			<column name="ip" field="ip" chs="ip" dbType="char" javaType="String"
				length="15" itemType="10" />
			<column name="lastReplyTime" field="lastReplyTime" chs="最后回帖时间" dbType="datetime" javaType="Date"
				itemType="30" listDisp="true" />
			<column name="lastUserName" field="lastUserName" chs="最后发帖人id" dbType="varchar" javaType="String"
				length="30" itemType="10" />
			<column name="lastNickName" field="lastNickName" chs="最后发帖人" dbType="varchar" javaType="String"
				length="30" itemType="10" />
			<column name="elite" field="elite" chs="是否精华" dbType="tinyint" javaType="Integer"
				length="1" itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column name="top" field="top" chs="是否置顶" dbType="tinyint" javaType="Integer"
				length="1" itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column name="lock" field="lock" chs="是否锁定" dbType="tinyint" javaType="Integer"
				length="1" itemType="50" listDisp="true" codeMapping="yesOrNo" />
			<column name="hidden" field="hidden" chs="是否隐藏" dbType="tinyint" javaType="Integer"
				length="1" itemType="50" listDisp="true" codeMapping="yesOrNo" />
		</table>
	</package>
</model>
