=== sakella6669/crudgenerator/crudgenerator/temp/catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3school.com.cn"
  xmlns="http://www.w3school.com.cn" elementFormDefault="qualified">
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cd" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string" minOccurs="1" />
              <xs:element name="artist" type="xs:string" minOccurs="1" />
              <xs:element name="country" type="xs:string" />
              <xs:element name="company" type="xs:string" />
              <xs:element name="price" type="xs:decimal" minOccurs="1" />
              <xs:element name="year" type="xs:positiveInteger" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sakella6669/crudgenerator/trunk/crudgenerator/temp/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="catalog.xsl"?>
<catalog
  xmlns="http://www.w3school.com.cn"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.w3school.com.cn catalog.xsd">
	<cd>
		<title>Empire Burlesque</title>
		<artist>Bob Dylan</artist>
		<country>USA</country>
		<company>Columbia</company>
        <price>10.90</price>
		<year>1985</year>
	</cd>
</catalog>
